[editor]
line-number = "relative"
bufferline = "always"

[keys.normal]
H = ":buffer-previous"
L = ":buffer-next"
C-q = ":buffer-close"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-k = "jump_view_up"
